### ISSUE TITLE
Milestone 0.0.2 Goals

### ISSUE THREAD

**Issue by Puddinglord** [Puddinglord/micro-ldap#4]
This will include the following:

- [x] The ability to create the micro-ldap object
  - Added with issue #3 
- [x] The ability to configure the micro-ldap object
  - Added with issue #3 
- [x] The ability to start and stop the micro-ldap object as an internal scheduled service
  - Basic support added with issue #3 
- [x] The ability to set password creation rules
  - Support added with issue #6 
- [x] The ability to enforce password creation rules
  - Support added with issue #6 
- [x] The ability to set password expiration
  - Support added with issue #7 
- [x] The ability to enforce password expiration
  - Support added with issue #7

**Comment by Puddinglord** [comment]
This looks good to go!

I think we are ready to publish to NPM!
